### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by tanglang96** [nischnei/depth_completion#1]
When I  run the file sparse_conv_net.py in spyder , there is an error in experiment.py line52 , AttributeError: 'Namespace' object has no attribute 'func' . Can you please help me solve this problem ? Is it because I run these codes in wrong way ?

**Comment by nischnei** [comment]
Hey, this code is still 'work in progress' - I just updated the whole code and switched it from KERAS to tensorflow only. If I find time tomorrow, I will update the readme as well.

**Comment by tanglang96** [comment]
ok, I got it, thanks for your reply

**Comment by DiscoDiscoBoomBoom** [comment]
It doesn't update yet

**Comment by mvoelk** [comment]
Okay, I wrote a SparseConv2D layer for TensorFlow Keras... [layers.py](https://github.com/mvoelk/keras_layers/blob/master/layers.py)

**Comment by nischnei** [comment]
I made some major changes now, please let me know if you have still trouble in using it.
