### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by Liuchongpei** [nischnei/depth_completion#2]
Hi,  Nischnei！Could you please write a more specific usage?

**Comment by nischnei** [comment]
Hey @Liuchongpei 

thanks for your message! This code has not really been published on the KITTI page. One reason is, that there are still bugs and the documentation is limited. I will update this code soon as I will write my phd thesis on this basis. If you follow this repository you will get automatic updates!

**Comment by nischnei** [comment]
@Liuchongpei I added a better description in the README file, please tell me if you can understand the code better now.
