### ISSUE TITLE
Could you share the code for generating data sets? 

### ISSUE THREAD

**Issue by AbnerCSZ** [nischnei/depth_completion#4]
Hi @nischnei
Your work is very detailed and excellent, especially the generation of data sets.
Although there are references to the method of making data sets in the paper,**use the SGM depth maps only once to clean the accumulated laser scan projection, in order to remove all outliers in one step: Occlusions, dynamic motion and measurement artifacts.**.
It is unfortunate that no relevant code is seen on the Internet.
So could you share the code for generating data sets? I am a student and want to reproduce the results of this article and explore the impact of **dynamic** objects on data sets.
Thank you very much!

**Comment by maiminh1996** [comment]
@AbnerCSZ  have you resolved the problem?
